name: Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout project
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: 🔨 Investigate Node
        run: |
          npm ls -gp --depth=0
          ls -la ~
