name: Create database
on:
  schedule:
    - cron: '25 15 * * *'
  push:
    branches:
      - main
    paths:
      - _data/**
      - bin/**
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout project
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: 💎 Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Initialize database
        run: |
          python -m pip install --upgrade pip
          pip install csv-to-sqlite
          ./bin/initdb.sh

      - name: 🚀 Deploy to data branch
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: data-branch
          folder: data
