name: SQLite
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout project
        uses: actions/checkout@v2

      - name: SQLite
        run: |
          sqlite3 --version

